<?php

return [
  [
    'name' => 'Tagliere di Salumi',
    'description' => 'Vassoio con molto salumi',
    'price' => '12',
    'ingradiants' => 'Mortadella, Salame, Formaggi',
    'category' => 'Antipasto',
  ],
  [
    'name' => 'Tagliere di Salumi',
    'description' => 'Vassoio con diversi salumi',
    'price' => '10',
    'ingradiants' => 'Prosciutto, Salame, Formaggi',
    'category' => 'Antipasto',
  ],
  [
    'name' => 'Tagliere di Salumi e Formaggi',
    'description' => 'Vassoio con molto salumi',
    'price' => '15',
    'ingradiants' => 'Mortadella, Salame, Formaggi, Prosciutto',
    'category' => 'Antipasto',
  ],
  [
    'name' => 'Tagliere di Salumi',
    'description' => 'Vassoio con molto salumi',
    'price' => '8',
    'ingradiants' => 'Prosciutto, Mortadella, Salame, Formaggi',
    'category' => 'Antipasto',
  ],
  [
    'name' => 'Pizza Margherita',
    'description' => 'Classica Pizza Margherita',
    'price' => '7',
    'ingradiants' => 'Pomodoro, Mozzarella, Basilico',
    'category' => 'Secondo',
  ],
  [
    'name' => 'Pizza Margherita',
    'description' => 'Classica Pizza Margherita',
    'price' => '5.50',
    'ingradiants' => 'Pomodoro, Mozzarella, Basilico',
    'category' => 'Secondo',
  ],
  [
    'name' => 'Pizza Margherita',
    'description' => 'Classica Pizza Margherita',
    'price' => '6',
    'ingradiants' => 'Pomodoro, Mozzarella, Basilico',
    'category' => 'Secondo',
  ],
  [
    'name' => 'Pizza Margherita',
    'description' => 'Classica Pizza Margherita',
    'price' => '7.5',
    'ingradiants' => 'Pomodoro, Mozzarella, Basilico',
    'category' => 'Secondo',
  ],
  [
    'name' => 'Insalata di Mare',
    'description' => 'Insalata di Mare fresca',
    'price' => '8',
    'ingradiants' => 'Vari tipi di Pesce',
    'category' => 'Antipasto',
  ],
  [
    'name' => 'Insalata di Mare',
    'description' => 'Insalata di Mare fresca',
    'price' => '9',
    'ingradiants' => 'Vari tipi di Pesce',
    'category' => 'Antipasto',
  ],
  [
    'name' => 'Insalata di Mare',
    'description' => 'Insalata di Mare fresca',
    'price' => '9.50',
    'ingradiants' => 'Vari tipi di Pesce',
    'category' => 'Antipasto',
  ],
  [
    'name' => "Bucatini all'Amatriciana",
    'description' => 'Classici Spaghetti all Amatriciana',
    'price' => '7',
    'ingradiants' => 'Guanciale, Pomodoro, Pecorino',
    'category' => 'Primo',
  ],
  [
    'name' => "Bucatini all'Amatriciana",
    'description' => 'Classici Spaghetti all Amatriciana',
    'price' => '8',
    'ingradiants' => 'Guanciale, Pomodoro, Pecorino',
    'category' => 'Primo',
  ],
  [
    'name' => "Bucatini all'Amatriciana",
    'description' => 'Classici Spaghetti all Amatriciana',
    'price' => '5',
    'ingradiants' => 'Guanciale, Pomodoro, Pecorino',
    'category' => 'Primo',
  ],
  [
    'name' => 'Ravioli Burro e Salvia',
    'description' => 'Ravioli di carne fatti in casa',
    'price' => '8',
    'ingradiants' => 'Ravioli, Carne di Manzo, Salvia, Burro',
    'category' => 'Primo',
  ],
  [
    'name' => 'Ravioli Burro e Salvia',
    'description' => 'Ravioli di carne fatti in casa',
    'price' => '7',
    'ingradiants' => 'Ravioli, Carne di Manzo, Salvia, Burro',
    'category' => 'Primo',
  ],
  [
    'name' => 'Fegato alla Veneziana',
    'description' => 'Fegato alla veneziana classico',
    'price' => '6',
    'ingradiants' => 'Fegato, Cipolle',
    'category' => 'Secondo',
  ],
  [
    'name' => 'Fegato alla Veneziana',
    'description' => 'Fegato alla veneziana classico',
    'price' => '8',
    'ingradiants' => 'Fegato, Cipolle',
    'category' => 'Secondo',
  ],
  [
    'name' => 'Panino col Lampredotto',
    'description' => 'Panino col Lampredotto classico',
    'price' => '6',
    'ingradiants' => 'Lampredotto, Pane',
    'category' => 'Secondo',
  ],
  [
    'name' => 'Panino col Lampredotto',
    'description' => 'Panino col Lampredotto classico',
    'price' => '7',
    'ingradiants' => 'Lampredotto, Pane',
    'category' => 'Secondo',
  ],
  [
    'name' => 'Tiramisu',
    'description' => 'Tiramisu Classico',
    'price' => '5',
    'ingradiants' => 'Caffè, Mascarpone, Savoiardi',
    'category' => 'Dessert',
  ],
  [
    'name' => 'Tiramisu',
    'description' => 'Tiramisu Classico',
    'price' => '4',
    'ingradiants' => 'Caffè, Mascarpone, Savoiardi',
    'category' => 'Dessert',
  ],
  [
    'name' => 'Panna Cotta',
    'description' => 'Panna Cotta classica',
    'price' => '5',
    'ingradiants' => 'PannaCotta, Vaniglia',
    'category' => 'Dessert',
  ],
  [
    'name' => 'Panna Cotta',
    'description' => 'Panna Cotta classica',
    'price' => '6',
    'ingradiants' => 'PannaCotta, Vaniglia',
    'category' => 'Dessert',
  ],
  [
    'name' => 'Macedonia di Frutta',
    'description' => 'Macedonia di stagione',
    'price' => '5',
    'ingradiants' => 'Fragole, Banane, Pesca',
    'category' => 'Frutta',
  ],
  [
    'name' => 'Macedonia di Frutta',
    'description' => 'Macedonia di stagione',
    'price' => '5',
    'ingradiants' => 'Fragole, Banane, Pesca',
    'category' => 'Frutta',
  ],
  [
    'name' => 'Macedonia di Frutta',
    'description' => 'Macedonia di stagione',
    'price' => '5',
    'ingradiants' => 'Fragole, Banane, Pesca',
    'category' => 'Frutta',
  ],
  [
    'name' => 'Macedonia di Frutta',
    'description' => 'Macedonia di stagione',
    'price' => '5',
    'ingradiants' => 'Fragole, Banane, Pesca',
    'category' => 'Frutta',
  ],
  [
    'name' => 'Patatine Fritte',
    'description' => 'Patatine Fritte',
    'price' => '4',
    'ingradiants' => 'Patate, Olio, Sale',
    'category' => 'Contorno',
  ],
  [
    'name' => 'Patatine Fritte',
    'description' => 'Patatine Fritte',
    'price' => '4',
    'ingradiants' => 'Patate, Olio, Sale',
    'category' => 'Contorno',
  ],
  [
    'name' => 'Patatine Fritte',
    'description' => 'Patatine Fritte',
    'price' => '4',
    'ingradiants' => 'Patate, Olio, Sale',
    'category' => 'Contorno',
  ],
];